[functions]
node_bundler = "esbuild"
external_node_modules = ["@modelcontextprotocol/sdk", "storyblok-js-client"]
included_files = [".env"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/index"
status = 200
